name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Run Flutter analyze
      run: flutter analyze --no-pub
    
    - name: Run Flutter tests with coverage
      run: |
        flutter test --coverage
        # Install lcov and generate HTML coverage report
        sudo apt-get update && sudo apt-get install -y lcov
        lcov --summary coverage/lcov.info
        genhtml coverage/lcov.info -o coverage/html

  build:
    name: Build
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: web
          - os: windows-latest
            platform: windows
          - os: ubuntu-latest
            platform: android
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Java 11 (Android only)
      if: matrix.platform == 'android'
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Set up Android SDK (Android only)
      if: matrix.platform == 'android'
      uses: android-actions/setup-android@v2
    
    - name: Accept Android licenses (Android only)
      if: matrix.platform == 'android'
      run: |
        yes | sdkmanager --licenses || true
        flutter doctor --android-licenses --verbose
    
    - name: Build Web
      if: matrix.platform == 'web'
      run: flutter build web --release
    
    - name: Build Windows
      if: matrix.platform == 'windows'
      run: flutter build windows --release
    
    - name: Build Android APK
      if: matrix.platform == 'android'
      run: |
        flutter build apk --release --split-per-abi
        ls -la build/app/outputs/flutter-apk/
    
    - name: Upload APK artifact (Android only)
      if: matrix.platform == 'android' && github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: android-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 5

  deploy-web:
    name: Deploy Web
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build/web
        branch: gh-pages
        clean: true
